### Route Login classique sans JWT

POST http://localhost:8888/v1/login HTTP/1.1
content-type: application/json

{
    "email": "",
    "password": "#0clock$0087"
}

### Route de login avec JWT

POST http://localhost:8888/v1/jwt/login HTTP/1.1
content-type: application/json

{
    "email": "test2@test.fr",
    "password": "#0clock$0087"
}

### Route protégée uniquement accéssible avec token valide

GET http://localhost:8888/v1/secret HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzI5MDM3NCwiZXhwIjoxNjQzMjkwNjc0fQ._6itYiWFu3GglAbZ5rMzxZp-g7OonhaB0xzwlQNIusE

### Refresh token

GET http://localhost:8888/v1/jwt/refresh/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzI4ODc5MSwiZXhwIjoxNjQ1ODgwNzkxfQ.-Msyd9MlJPnmsbdtqt3ChWFI9_fSsJdoFjRR-PESpqc HTTP/1.1
content-type: application/json

###

GET http://localhost:8888/v1/cryptos/usd/10
Content-Type: application/json

###

GET http://localhost:8888/v1/cryptos
Content-Type: application/json

###

GET http://localhost:8888/v1/crypto/bitcoin/
Content-Type: application/json
###

GET http://localhost:8888/v1/cryptoprice/bitcoin,ethereum/usd
Content-Type: application/json
###

GET http://localhost:8888/v1/trending
Content-Type: application/json
###

GET http://localhost:8888/v1/portfolio/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJlbWFpbCI6InRlc3QzQHRlc3QuZnIiLCJuaWNrbmFtZSI6InRlc3QzIiwicGljdHVyZSI6ImNvb2wifSwiaWF0IjoxNjQzNTY2NDUzLCJleHAiOjE2NDM1NjY3NTN9.EKTR8yShaYRMNNYu9OuPZwxp1SnjNXZzszCFoodktYU

### ATTENTION LA ROUTE ADD TRANSACTION EST ACCESSIBLE A UN USER CONNECTE AVEC UN MAUVAIS WALLET

POST http://localhost:8888/v1/portfolio/wallet/1/transaction/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzYzMDkzMiwiZXhwIjoxNjQzNjMxMjMyfQ.2QY98sPOijmFR5jaL7YouSJUJGCVraqoQCTwQQOW02U

{
  "id": 16,
  "buy": true,
  "buy_date": "Fri Jan 28 2022 15:20:46 GMT+0100",
  "coin_id": "compound-ether",
  "price": 1000,
  "quantity": 10,
  "symbol": "ceth"
}

### 

POST http://localhost:8888/v1/portfolio/wallet HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzYzMDQyMywiZXhwIjoxNjQzNjMwNzIzfQ.Tc523V6fJ7NDcitNHC_SdoHewFSNJPoasq4OWqqISDI

{
  "label": "testt wallet"
}

###

POST http://localhost:8888/v1/signup HTTP/1.1
content-type: application/json

{
  "email": "test3@test.fr",
  "nickname": "test3",
  "password": "#Cafard0087",
  "passwordCheck": "#Cafard0087",
  "picture": "cool"
}

###

POST http://localhost:8888/v1/jwt/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.fr",
    "password": "#0clock$0087"
}

### 

DELETE http://localhost:8888/v1/portfolio/transaction/6 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzYyNjcxNCwiZXhwIjoxNjQzNjI3MDE0fQ.9fe7N5DOt1OsfU3izhMvNBhXbPaMV8zt1mG-Kx5MQ_k

### 

DELETE http://localhost:8888/v1/portfolio/wallet/10 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzYzMDM4NywiZXhwIjoxNjQzNjMwNjg3fQ.FpX5niLylRNfOL1E7IHwMhgop1Is98uz_iZDO-iA684

