### Route Login classique sans JWT

POST http://localhost:8888/v1/login HTTP/1.1
content-type: application/json

{
    "email": "",
    "password": "#0clock$0087"
}

### Route de login avec JWT

POST http://localhost:8888/v1/jwt/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.fr",
    "password": "#0clock$0087"
}

### Route protégée uniquement accéssible avec token valide

GET http://localhost:8888/v1/secret HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzI5MDM3NCwiZXhwIjoxNjQzMjkwNjc0fQ._6itYiWFu3GglAbZ5rMzxZp-g7OonhaB0xzwlQNIusE

### Refresh token

GET http://localhost:8888/v1/jwt/refresh/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzI4ODc5MSwiZXhwIjoxNjQ1ODgwNzkxfQ.-Msyd9MlJPnmsbdtqt3ChWFI9_fSsJdoFjRR-PESpqc HTTP/1.1
content-type: application/json

###

GET http://localhost:8888/v1/cryptos/usd/10
Content-Type: application/json

###

GET http://localhost:8888/v1/cryptos
Content-Type: application/json

###

GET http://localhost:8888/v1/global
Content-Type: application/json

###

GET http://localhost:8888/v1/history/bitcoin/12-12-2015
Content-Type: application/json

###

GET http://localhost:8888/v1/crypto/bitcoin
Content-Type: application/json
###

GET http://localhost:8888/v1/cryptoprice/bitcoin,ethereum/usd
Content-Type: application/json
###

GET http://localhost:8888/v1/trending
Content-Type: application/json
###

GET http://localhost:8888/v1/portfolio/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0NDQyNDY4MCwiZXhwIjoxNjQ0NDI0OTgwfQ.ej0_D0ujm6dwpQ2YQ75SpCV2iKp54OSLgUxu7lnq2m4

###

GET http://localhost:8888/v1/portfolio/wallet/4
Content-Type: application/json
Authorization: 
### ATTENTION LA ROUTE ADD TRANSACTION EST ACCESSIBLE A UN USER CONNECTE AVEC UN MAUVAIS WALLET

POST http://localhost:8888/v1/portfolio/wallet/5/transaction/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0NDQyNDY4MCwiZXhwIjoxNjQ0NDI0OTgwfQ.ej0_D0ujm6dwpQ2YQ75SpCV2iKp54OSLgUxu7lnq2m4

{
  "buy": false,
  "buy_date": "Fri Jan 28 2022 15:20:46 GMT+0100",
  "coin_id": "bitcoin",
  "price": 1000,
  "quantity": -1,
  "symbol": "btc"
}

### 

POST http://localhost:8888/v1/portfolio/wallet HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0NDQyNDY4MCwiZXhwIjoxNjQ0NDI0OTgwfQ.ej0_D0ujm6dwpQ2YQ75SpCV2iKp54OSLgUxu7lnq2m4

{
  "label": "test3"
}

###

POST http://localhost:8888/v1/signup HTTP/1.1
content-type: application/json

{
  "email": "test10@test.fr",
  "nickname": "test3",
  "password": "#Cafard0087",
  "passwordCheck": "#Cafard0087",
  "picture": "cool"
}

###

POST http://localhost:8888/v1/jwt/login HTTP/1.1
content-type: application/json

{
    "email": "test3@test.fr",
    "password": "#0clock$0087"
}

### 

DELETE http://localhost:8888/v1/portfolio/transaction/1 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0Mzc0MjQzMCwiZXhwIjoxNjQzNzQyNzMwfQ.bsoKIznVugJszpK_rMOqpIX0ZJ4yKjJ7G0Wai54scVo

### 

DELETE http://localhost:8888/v1/portfolio/wallet/13 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5mciIsIm5pY2tuYW1lIjoidGVzdCIsInBpY3R1cmUiOiJodHRwczovL2Nkbi5pY29uLWljb25zLmNvbS9pY29uczIvMTM3MS9QTkcvNTEyL3JvYm90MDNfOTA4MzMucG5nIn0sImlhdCI6MTY0MzkyNTMxMywiZXhwIjoxNjQzOTI1NjEzfQ.jf9hkWF1iZdclCs7DTx7YXllL9pROaz1sQOmeYbPswI
