### Route Login classique sans JWT

POST http://localhost:8888/v1/login HTTP/1.1
content-type: application/json

{
    "email": "",
    "password": "#0clock$0087"
}

### Route de login avec JWT

POST http://localhost:8888/v1/jwt/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.fr",
    "password": "#0clock$0087"
}

### Route protégée uniquement accéssible avec token valide

GET http://localhost:8888/v1/secret HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJlbWFpbCI6InRlc3QyQHRlc3QuZnIiLCJuaWNrbmFtZSI6InRlc3QyIiwicGljdHVyZSI6Imh0dHBzOi8vY2RuLmljb24taWNvbnMuY29tL2ljb25zMi8xMzcxL1BORy81MTIvcm9ib3QwM185MDgzMy5wbmcifSwiaWF0IjoxNjQyODY5ODcwLCJleHAiOjE2NDI4NzAxNzB9.4X1RO9L6jvfNjIJvDtZvWHU7Yp6A14TU9vHch8hMUdc
### Refresh token

GET http://localhost:8888/v1/jwt/refresh/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJlbWFpbCI6InRlc3QyQHRlc3QuZnIiLCJuaWNrbmFtZSI6InRlc3QyIiwicGljdHVyZSI6Imh0dHBzOi8vY2RuLmljb24taWNvbnMuY29tL2ljb25zMi8xMzcxL1BORy81MTIvcm9ib3QwM185MDgzMy5wbmcifSwiaWF0IjoxNjQyODA5MTExLCJleHAiOjE2NDU0MDExMTF9.VhQCSCHJEHW6qldQNzsOh1Kr93ERySGgBw2DX9AKaxM HTTP/1.1
content-type: application/json

###

GET http://localhost:8888/v1/cryptos/usd/10
Content-Type: application/json

###

GET http://localhost:8888/v1/cryptos
Content-Type: application/json

###

GET http://localhost:8888/v1/crypto/bitcoin/
Content-Type: application/json
###

GET http://localhost:8888/v1/cryptoprice/bitcoin,ethereum/usd
Content-Type: application/json
###

GET http://localhost:8888/v1/trending
Content-Type: application/json
###

GET http://localhost:8888/v1/portfolio/1
Content-Type: application/json