# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    paths:
      - "front/**"
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted
    defaults:
       run:
         working-directory: "/home/prod/server/mycryptofolio/front"

    steps:
    - run: git pull
    - run: yarn
    - run: yarn clean
    - run: yarn build
    - run: ./updateMcf.sh
