name: deployment-back

on:
  push:
    paths:
      - "back/**"
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted
    defaults:
       run:
         working-directory: "/home/prod/server/mycryptofolio/back"

    steps:
    - run: git pull
    - run: npm i
    - run: sqitch deploy
    - run: pm2 restart mcf
