name: deployment-front

on:
  push:
    paths:
      - "front/**"
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted
    defaults:
       run:
         working-directory: "/home/prod/server/mycryptofolio/front"

    steps:
    - run: git pull
    - run: yarn
    - run: yarn clean
    - run: yarn build
    - run: ./updateMcf.sh
